services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: gaia
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: gaia
    volumes:
      - gaia-db-data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    ports:
      - "5433:5432"

  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://gaia:mysecretpassword@db:5432/gaia

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://gaia:mysecretpassword@db:5432/gaia
    ports:
      - "8000:8000"

volumes:
  gaia-db-data: